# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainctl < Formula
  desc "CLI for the Chainguard Platform"
  homepage "https://chainguard.dev"
  version "0.2.266"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.enforce.dev/chainctl/0.2.266/chainctl_darwin_x86_64"
      sha256 "6337a186c432c6eae0c8edc1630d3b2da6a0e8a70b9651ff157984548a06763f"

      define_method(:install) do
        bin.install "chainctl_darwin_x86_64" => "chainctl"
        bin.install_symlink "chainctl" => "docker-credential-cgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.enforce.dev/chainctl/0.2.266/chainctl_darwin_arm64"
      sha256 "aca9f2e4f40e549b6ec32c81396a5aa96c13f9119801df2b34229da28a2f49b2"

      define_method(:install) do
        bin.install "chainctl_darwin_arm64" => "chainctl"
        bin.install_symlink "chainctl" => "docker-credential-cgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.enforce.dev/chainctl/0.2.266/chainctl_linux_x86_64"
      sha256 "fd8135f15d968ff490de6b00e247ea367919499c27c67e80b5386689da665130"
      define_method(:install) do
        bin.install "chainctl_linux_x86_64" => "chainctl"
        bin.install_symlink "chainctl" => "docker-credential-cgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.enforce.dev/chainctl/0.2.266/chainctl_linux_arm64"
      sha256 "2f7fcc026b078b683f2f34136eb618553860c4b30e7f6120d8b803fc6b9b80b0"
      define_method(:install) do
        bin.install "chainctl_linux_arm64" => "chainctl"
        bin.install_symlink "chainctl" => "docker-credential-cgr"
      end
    end
  end

  test do
    system "#{bin}/chainctl", "version"
  end
end
