# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chainctl < Formula
  desc "CLI for the Chainguard Platform"
  homepage "https://chainguard.dev"
  version "0.1.289"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.enforce.dev/chainctl/0.1.289/chainctl_darwin_x86_64"
      sha256 "53d214c7dd2b71e17e14484a309255d588e47b0f673a89650ecb8ab0030d7c2e"

      def install
        bin.install "chainctl_darwin_x86_64" => "chainctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.enforce.dev/chainctl/0.1.289/chainctl_darwin_arm64"
      sha256 "b305f46c9318809088c1afedeb2879a741f21d2961361c05abcb0be072bc0d57"

      def install
        bin.install "chainctl_darwin_arm64" => "chainctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://dl.enforce.dev/chainctl/0.1.289/chainctl_linux_x86_64"
      sha256 "7090f49b05f4f36875569e0351a342e80d260b494aa45073d230d9ab4823f9b8"

      def install
        bin.install "chainctl_linux_x86_64" => "chainctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.enforce.dev/chainctl/0.1.289/chainctl_linux_arm64"
      sha256 "363d45c0d36f688205a6ea927266496412add81723e90335f73c047e4ca49a9d"

      def install
        bin.install "chainctl_linux_arm64" => "chainctl"
      end
    end
  end

  test do
    system "#{bin}/chainctl", "version"
  end
end
