# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfc < Formula
  desc "Convert Dockerfiles to use Chainguard"
  homepage "https://github.com/chainguard-dev/dfc"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chainguard-dev/dfc/releases/download/v0.3.0/dfc_0.3.0_darwin_amd64.tar.gz"
      sha256 "b96d1e7b3424e01dc277016050e6d62e924bc6bb7c98e51fabc304e7bed6aa62"

      def install
        bin.install "dfc" => "dfc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chainguard-dev/dfc/releases/download/v0.3.0/dfc_0.3.0_darwin_arm64.tar.gz"
      sha256 "84ea3ba1606f7639f343869f9bbcd8247120e606eb690d5331ba766aeb831b57"

      def install
        bin.install "dfc" => "dfc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chainguard-dev/dfc/releases/download/v0.3.0/dfc_0.3.0_linux_amd64.tar.gz"
        sha256 "6df674e2554a865321a8cbe2640d502b81dd1f473feb11f023ebef5edc6bae5c"

        def install
          bin.install "dfc" => "dfc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chainguard-dev/dfc/releases/download/v0.3.0/dfc_0.3.0_linux_arm64.tar.gz"
        sha256 "fcd3a894175009b74a0ac35e400ca0b3e4fe7e1b0e9c43ecb93f98fe3296ac55"

        def install
          bin.install "dfc" => "dfc"
        end
      end
    end
  end

  test do
    system "#{bin}/dfc", "--version"
  end
end
