# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dfc < Formula
  desc "Convert Dockerfiles to use Chainguard"
  homepage "https://github.com/chainguard-dev/dfc"
  version "0.9.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chainguard-dev/dfc/releases/download/v0.9.3/dfc_0.9.3_darwin_amd64.tar.gz"
      sha256 "ac0e65b5a4fec9c565d69c51f4f60e483636cd661539a750fb101e4b2dddd2e7"

      def install
        bin.install "dfc" => "dfc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chainguard-dev/dfc/releases/download/v0.9.3/dfc_0.9.3_darwin_arm64.tar.gz"
      sha256 "66ac7873859f588846bdc26856d8336f7a239064ac8b97c181e66d9d02bf0ed3"

      def install
        bin.install "dfc" => "dfc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/chainguard-dev/dfc/releases/download/v0.9.3/dfc_0.9.3_linux_amd64.tar.gz"
      sha256 "9facf9867869ee737ba4c887be249742e1a8586e39ba29f9685f5aeee2eb0695"
      def install
        bin.install "dfc" => "dfc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/chainguard-dev/dfc/releases/download/v0.9.3/dfc_0.9.3_linux_arm64.tar.gz"
      sha256 "028b31761d0cf5f0bbc2e2fac622362797aa1cc2cb0d953d15d9ecab612c09f8"
      def install
        bin.install "dfc" => "dfc"
      end
    end
  end

  test do
    system "#{bin}/dfc", "--version"
  end
end
