# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Melange < Formula
  desc "Build apk packages using declarative pipelines"
  homepage "https://github.com/chainguard-dev/melange"
  version "0.18.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chainguard-dev/melange/releases/download/v0.18.2/melange_0.18.2_darwin_amd64.tar.gz"
      sha256 "2af570dbd3bf54b780b6f4c55780c54046c5c15f56b14075278ec64c3521449a"

      def install
        bin.install "melange" => "melange"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chainguard-dev/melange/releases/download/v0.18.2/melange_0.18.2_darwin_arm64.tar.gz"
      sha256 "cc8bc8ab4d2504b0dd2f702a7d3c86b4d319ea5816c051ad2b42a24ac9d6d5bf"

      def install
        bin.install "melange" => "melange"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chainguard-dev/melange/releases/download/v0.18.2/melange_0.18.2_linux_amd64.tar.gz"
        sha256 "541e7c4fc00a6ba81becbce37c12f0419427d2eeb1747dd3f16b7f9238583280"

        def install
          bin.install "melange" => "melange"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chainguard-dev/melange/releases/download/v0.18.2/melange_0.18.2_linux_arm64.tar.gz"
        sha256 "eed6bcb53a445289009612af77d14238571a04f848e3a30cf655b50a040a5019"

        def install
          bin.install "melange" => "melange"
        end
      end
    end
  end

  test do
    system "#{bin}/melange", "version"
  end
end
