# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Melange < Formula
  desc "Build apk packages using declarative pipelines"
  homepage "https://github.com/chainguard-dev/melange"
  version "0.17.5"

  on_macos do
    on_intel do
      url "https://github.com/chainguard-dev/melange/releases/download/v0.17.5/melange_0.17.5_darwin_amd64.tar.gz"
      sha256 "4d1de1d8ce80881428b1c28ce556865f94c600f58987870a474f2886ff70140c"

      def install
        bin.install "melange" => "melange"
      end
    end
    on_arm do
      url "https://github.com/chainguard-dev/melange/releases/download/v0.17.5/melange_0.17.5_darwin_arm64.tar.gz"
      sha256 "c2e2e30e013e742b8d182a6ca5a08526ba357a3deeda89d842419da1b1ccb5a9"

      def install
        bin.install "melange" => "melange"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chainguard-dev/melange/releases/download/v0.17.5/melange_0.17.5_linux_amd64.tar.gz"
        sha256 "49f0866dd3a652c481c6ff27c68c11fd60d37c09bf647b3490be5105db8b361b"

        def install
          bin.install "melange" => "melange"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chainguard-dev/melange/releases/download/v0.17.5/melange_0.17.5_linux_arm64.tar.gz"
        sha256 "db9731046546c0bd9e64c893320b95d0d47214bac091e500474a4a4b408df1b6"

        def install
          bin.install "melange" => "melange"
        end
      end
    end
  end

  test do
    system "#{bin}/melange", "version"
  end
end
